version: "3.7"
services:
  nginx-proxy:
    build:
      context: ../backend/proxy
      dockerfile: nginx.Dockerfile
    restart: always
    volumes:
      - ../backend/proxy/config/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx-proxy
    ports:
      - "80:80"

    depends_on:
      - mvc-landing
  mvc-landing:
    build: 
      context: ../backend/apis/mvc.landing
      dockerfile: express.Dockerfile
    container_name: express-mvc-landing
    restart: always
    volumes:
      - ../backend/apis/mvc.landing:/usr/src/app
      - ../backend/database/mock:/usr/src/app/database
      - /usr/src/app/node_modules
    depends_on:
      - public-service

  public-service:
    build: 
      context: ../backend/public
      dockerfile: public.Dockerfile
    container_name: public-service
    restart: always
    volumes:
      - ../backend/public/config/default.conf:/etc/nginx/conf.d/default.conf
      - ../assets/dist:/data/public/
      - ../frontend/landing/dist:/data/public/landing/
